/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abood
 */
public class frmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form frmDashboard
     */
    public frmDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        All = new javax.swing.JPanel();
        cmbAccount = new javax.swing.JComboBox<>();
        pnlCards = new javax.swing.JPanel();
        pnlCardTotalAppointment = new javax.swing.JPanel();
        lblTitleTotalAppointment = new javax.swing.JLabel();
        lblCountTotalAppointment = new javax.swing.JLabel();
        pnlCardTotalCustomers = new javax.swing.JPanel();
        lblTitleTotalCustomers = new javax.swing.JLabel();
        lblCountTotalCustomers = new javax.swing.JLabel();
        pnlCardUpcomingSessions = new javax.swing.JPanel();
        lblTitleUpcomingSessions = new javax.swing.JLabel();
        lblCountUpcomingSessions = new javax.swing.JLabel();
        pnlCardTotalRevenue = new javax.swing.JPanel();
        lblTitleTotalRevenue = new javax.swing.JLabel();
        lblCountTotalRevenue = new javax.swing.JLabel();
        tblUpcomingSessions = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlQuickActions = new javax.swing.JPanel();
        btnNewAppointment = new javax.swing.JButton();
        btnNewCostomers = new javax.swing.JButton();
        btnViewCalenser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setResizable(false);

        cmbAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account 1", "Account 2", "Account 3" }));
        cmbAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccountActionPerformed(evt);
            }
        });

        pnlCardTotalAppointment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitleTotalAppointment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitleTotalAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleTotalAppointment.setText("Total Appointment");

        lblCountTotalAppointment.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCountTotalAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountTotalAppointment.setText("12");

        javax.swing.GroupLayout pnlCardTotalAppointmentLayout = new javax.swing.GroupLayout(pnlCardTotalAppointment);
        pnlCardTotalAppointment.setLayout(pnlCardTotalAppointmentLayout);
        pnlCardTotalAppointmentLayout.setHorizontalGroup(
            pnlCardTotalAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardTotalAppointmentLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlCardTotalAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCountTotalAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleTotalAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlCardTotalAppointmentLayout.setVerticalGroup(
            pnlCardTotalAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardTotalAppointmentLayout.createSequentialGroup()
                .addComponent(lblTitleTotalAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountTotalAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pnlCardTotalCustomers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitleTotalCustomers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitleTotalCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleTotalCustomers.setText("Total Customers");

        lblCountTotalCustomers.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCountTotalCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountTotalCustomers.setText("150");

        javax.swing.GroupLayout pnlCardTotalCustomersLayout = new javax.swing.GroupLayout(pnlCardTotalCustomers);
        pnlCardTotalCustomers.setLayout(pnlCardTotalCustomersLayout);
        pnlCardTotalCustomersLayout.setHorizontalGroup(
            pnlCardTotalCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardTotalCustomersLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlCardTotalCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCountTotalCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleTotalCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlCardTotalCustomersLayout.setVerticalGroup(
            pnlCardTotalCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardTotalCustomersLayout.createSequentialGroup()
                .addComponent(lblTitleTotalCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountTotalCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pnlCardUpcomingSessions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitleUpcomingSessions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitleUpcomingSessions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleUpcomingSessions.setText("Upcoming Sessions");

        lblCountUpcomingSessions.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCountUpcomingSessions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountUpcomingSessions.setText("6");

        javax.swing.GroupLayout pnlCardUpcomingSessionsLayout = new javax.swing.GroupLayout(pnlCardUpcomingSessions);
        pnlCardUpcomingSessions.setLayout(pnlCardUpcomingSessionsLayout);
        pnlCardUpcomingSessionsLayout.setHorizontalGroup(
            pnlCardUpcomingSessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardUpcomingSessionsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlCardUpcomingSessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCountUpcomingSessions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleUpcomingSessions, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlCardUpcomingSessionsLayout.setVerticalGroup(
            pnlCardUpcomingSessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardUpcomingSessionsLayout.createSequentialGroup()
                .addComponent(lblTitleUpcomingSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCountUpcomingSessions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCardTotalRevenue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitleTotalRevenue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitleTotalRevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleTotalRevenue.setText("Total Revenue");

        lblCountTotalRevenue.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCountTotalRevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountTotalRevenue.setText("1250 JD");

        javax.swing.GroupLayout pnlCardTotalRevenueLayout = new javax.swing.GroupLayout(pnlCardTotalRevenue);
        pnlCardTotalRevenue.setLayout(pnlCardTotalRevenueLayout);
        pnlCardTotalRevenueLayout.setHorizontalGroup(
            pnlCardTotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardTotalRevenueLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlCardTotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCountTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlCardTotalRevenueLayout.setVerticalGroup(
            pnlCardTotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardTotalRevenueLayout.createSequentialGroup()
                .addComponent(lblTitleTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout pnlCardsLayout = new javax.swing.GroupLayout(pnlCards);
        pnlCards.setLayout(pnlCardsLayout);
        pnlCardsLayout.setHorizontalGroup(
            pnlCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCardTotalAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCardTotalCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCardUpcomingSessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCardTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlCardsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnlCardTotalAppointment, pnlCardTotalCustomers, pnlCardTotalRevenue, pnlCardUpcomingSessions});

        pnlCardsLayout.setVerticalGroup(
            pnlCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pnlCardTotalAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCardUpcomingSessions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCardTotalCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCardTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblUpcomingSessions.setToolTipText("");
        tblUpcomingSessions.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10:00 AM", "Ahmad ALi", "Baraa", "Confirmed"},
                {"11:15 AM", "Sara", "Am Yamen", "Pendinf"},
                {null, null, null, null},
                {null, null, null, null},
                {null, "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Time", "Customer", "Staff", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(50);
        tblUpcomingSessions.setViewportView(jTable1);

        pnlQuickActions.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quick Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        btnNewAppointment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNewAppointment.setText("New Appointment");
        btnNewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAppointmentActionPerformed(evt);
            }
        });

        btnNewCostomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNewCostomers.setText("New Costomers");
        btnNewCostomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCostomersActionPerformed(evt);
            }
        });

        btnViewCalenser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewCalenser.setText("View Calenser (Coming Soon)");

        javax.swing.GroupLayout pnlQuickActionsLayout = new javax.swing.GroupLayout(pnlQuickActions);
        pnlQuickActions.setLayout(pnlQuickActionsLayout);
        pnlQuickActionsLayout.setHorizontalGroup(
            pnlQuickActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuickActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnNewCostomers, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewCalenser, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuickActionsLayout.setVerticalGroup(
            pnlQuickActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuickActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQuickActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCalenser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewCostomers, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout AllLayout = new javax.swing.GroupLayout(All);
        All.setLayout(AllLayout);
        AllLayout.setHorizontalGroup(
            AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllLayout.createSequentialGroup()
                .addGroup(AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AllLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AllLayout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlQuickActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(AllLayout.createSequentialGroup()
                                .addComponent(tblUpcomingSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 5, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AllLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        AllLayout.setVerticalGroup(
            AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAccount)
                .addGap(174, 174, 174)
                .addComponent(tblUpcomingSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlQuickActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AllLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(564, Short.MAX_VALUE)))
        );

        getContentPane().add(All, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAccountActionPerformed

    private void btnNewCostomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCostomersActionPerformed
        // TODO add your handling code here:
        frmNewCustomer frmCustomer = new frmNewCustomer();
        frmCustomer.setVisible(true);
        
    }//GEN-LAST:event_btnNewCostomersActionPerformed

    private void btnNewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAppointmentActionPerformed
        
        
        frmNewAppointment frmAppointment = new frmNewAppointment();
        frmAppointment.setVisible(true);
        
        
    }//GEN-LAST:event_btnNewAppointmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel All;
    private javax.swing.JButton btnNewAppointment;
    private javax.swing.JButton btnNewCostomers;
    private javax.swing.JButton btnViewCalenser;
    private javax.swing.JComboBox<String> cmbAccount;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCountTotalAppointment;
    private javax.swing.JLabel lblCountTotalCustomers;
    private javax.swing.JLabel lblCountTotalRevenue;
    private javax.swing.JLabel lblCountUpcomingSessions;
    private javax.swing.JLabel lblTitleTotalAppointment;
    private javax.swing.JLabel lblTitleTotalCustomers;
    private javax.swing.JLabel lblTitleTotalRevenue;
    private javax.swing.JLabel lblTitleUpcomingSessions;
    private javax.swing.JPanel pnlCardTotalAppointment;
    private javax.swing.JPanel pnlCardTotalCustomers;
    private javax.swing.JPanel pnlCardTotalRevenue;
    private javax.swing.JPanel pnlCardUpcomingSessions;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlQuickActions;
    private javax.swing.JScrollPane tblUpcomingSessions;
    // End of variables declaration//GEN-END:variables
}
